# Generated by Django 4.2 on 2023-04-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customuser_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="connection_id",
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
